### ISSUE TITLE
I found your secret repo :grin:

### ISSUE THREAD

**Issue by schlimmchen** [helgenachlass/OpenDTU-OnBattery#4]
### What happened?

I looked really hard.

### To Reproduce Bug

one in a million find...

### Expected Behavior

should be easier to find.

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

asasdcasdc

### What firmware variant (PIO Environment) are you using?

this should be a dropdown...

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by helgenachlass** [comment]
Go away!

**Comment by schlimmchen** [comment]
Oh, I can still comment here... Did not know that...
